apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
    environment: production
spec:
  containers:
  - name: httpd-container
    image: myrepo:latest   #<YOUR_DOCKER_REPO>:<tag>
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
    app: httpd
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: httpd-route
spec:
  to:
    kind: Service
    name: httpd-svc     # Internal service to route traffic to
  port:
    targetPort: 80      # Target port on the service
