apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-ctr
        image: public.ecr.aws/n7h7b7j8/my-aws-repo/webapp:latest   #<YOUR_DOCKER_REPO>:<tag>
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: webapp
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webapp-route
spec:
  to:
    kind: Service
    name: webapp-svc     # Internal service to route traffic to
  port:
    targetPort: 80      # Target port on the service
